# Generated by Django 3.2 on 2022-01-19 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchese',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
