# Generated by Django 3.2 on 2022-01-20 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_purchese_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchese',
            new_name='Purchase',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
