# Generated by Django 3.2 on 2022-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220120_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
